import { Routes } from '@angular/router';

import { DashboardComponent } from '../../pages/dashboard/dashboard.component';
import { IconsComponent } from '../../pages/icons/icons.component';
import { MapsComponent } from '../../pages/maps/maps.component';
import { UserProfileComponent } from '../../pages/user-profile/user-profile.component';
import { TablesComponent } from '../../pages/tables/tables.component';
import { ListUserComponent } from 'src/app/pages/user/list-user/list-user.component';
import { InfoUserComponent } from 'src/app/pages/user/info-user/info-user.component';
import { AddUserComponent } from 'src/app/pages/user/add-user/add-user.component';
import { UpdateUserComponent } from 'src/app/pages/user/update-user/update-user.component';
import { ListDEComponent } from 'src/app/pages/courrier/depart-externe/list-de/list-de.component';
import { AddDEComponent } from 'src/app/pages/courrier/depart-externe/add-de/add-de.component';
import { UpdateDEComponent } from 'src/app/pages/courrier/depart-externe/update-de/update-de.component';
import { ListDiComponent } from 'src/app/pages/courrier/depart-interne/list-di/list-di.component';
import { AddDiComponent } from 'src/app/pages/courrier/depart-interne/add-di/add-di.component';
import { UpdateDiComponent } from 'src/app/pages/courrier/depart-interne/update-di/update-di.component';
import { ListAeComponent } from 'src/app/pages/courrier/arrivee-externe/list-ae/list-ae.component';
import { AddAeComponent } from 'src/app/pages/courrier/arrivee-externe/add-ae/add-ae.component';
import { UpdateAeComponent } from 'src/app/pages/courrier/arrivee-externe/update-ae/update-ae.component';
import { ListArrAeroportComponent } from 'src/app/pages/courrier/arrivee-aeroport/list-arr-aeroport/list-arr-aeroport.component';
import { AddArrAeroportComponent } from 'src/app/pages/courrier/arrivee-aeroport/add-arr-aeroport/add-arr-aeroport.component';
import { UpdateArrAeroportComponent } from 'src/app/pages/courrier/arrivee-aeroport/update-arr-aeroport/update-arr-aeroport.component';
import { ListAppelOffreComponent } from 'src/app/pages/courrier/appel-offre/list-appel-offre/list-appel-offre.component';
import { AddAppelOffreComponent } from 'src/app/pages/courrier/appel-offre/add-appel-offre/add-appel-offre.component';
import { UpdateAppelOffreComponent } from 'src/app/pages/courrier/appel-offre/update-appel-offre/update-appel-offre.component';
import { ListDossiersComponent } from 'src/app/pages/dossier/list-dossiers/list-dossiers.component';
import { DetailDossierComponent } from 'src/app/pages/dossier/detail-dossier/detail-dossier.component';
import { SelectDossierComponent } from 'src/app/pages/dossier/select-dossier/select-dossier.component';
import { ListAffaireComponent } from 'src/app/pages/affaire/list-affaire/list-affaire.component';
import { AddAffaireComponent } from 'src/app/pages/affaire/add-affaire/add-affaire.component';
import { UpdateAffaireComponent } from 'src/app/pages/affaire/update-affaire/update-affaire.component';
import { ListTribunalComponent } from 'src/app/pages/tribunal/list-tribunal/list-tribunal.component';
import { AddTribunalComponent } from 'src/app/pages/tribunal/add-tribunal/add-tribunal.component';
import { UpdateHonoraireComponent } from 'src/app/pages/honoraire/update-honoraire/update-honoraire.component';
import { ListHonoraireComponent } from 'src/app/pages/honoraire/list-honoraire/list-honoraire.component';
import { AddHonoraireComponent } from 'src/app/pages/honoraire/add-honoraire/add-honoraire.component';

export const AdminLayoutRoutes: Routes = [
    { path: 'dashboard',      component: DashboardComponent },
    { path: 'user-profile',   component: UserProfileComponent },
    { path: 'tables',         component: TablesComponent },
    { path: 'icons',          component: IconsComponent },
    { path: 'maps',           component: MapsComponent },
    { path: 'list-user',           component: ListUserComponent },
    { path: 'info-user/:id',           component: InfoUserComponent },
    { path: 'add-user',           component: AddUserComponent },
    { path: 'update-user/:id',           component: UpdateUserComponent },
    { path: 'list-de',           component: ListDEComponent },
    { path: 'add-de',           component: AddDEComponent },
    { path: 'update-de/:numeroCourrier',           component: UpdateDEComponent },
    { path: 'list-di',           component: ListDiComponent },
    { path: 'add-di',           component: AddDiComponent },
    { path: 'update-di/:numeroCourrier',           component: UpdateDiComponent },
    { path: 'list-ae',           component: ListAeComponent },
    { path: 'add-ae',           component: AddAeComponent },
    { path: 'update-ae/:numeroCourrier',           component: UpdateAeComponent },
    { path: 'list-arrAeroport',           component: ListArrAeroportComponent },
    { path: 'add-arrAeroport',           component: AddArrAeroportComponent },
    { path: 'update-arrAeroport/:numeroCourrier',           component: UpdateArrAeroportComponent },
    { path: 'list-appOffre',           component: ListAppelOffreComponent },
    { path: 'add-appOffre',           component: AddAppelOffreComponent },
    { path: 'update-appOffre/:numeroCourrier',           component: UpdateAppelOffreComponent },
    { path: 'list-dossiers',           component: ListDossiersComponent },
    { path: 'detail-dossier/:idDossier',           component: DetailDossierComponent },
    { path: 'select-dossier/:numeroCourrier',           component: SelectDossierComponent },
    { path: 'list-affaire',           component: ListAffaireComponent },
    { path: 'add-affaire',           component: AddAffaireComponent },
    { path: 'update-affaire/:idAffaire',           component: UpdateAffaireComponent },
    { path: 'list-tribunal',           component: ListTribunalComponent },
    { path: 'add-tribunal',           component: AddTribunalComponent },
    { path: 'update-honoraire/:idHonoraire',           component: UpdateHonoraireComponent },
    { path: 'list-honoraire',           component: ListHonoraireComponent },
    { path: 'add-honoraire',           component: AddHonoraireComponent }

];
